stages:
  - test
  - build


variables:
  PYTHONUNBUFFERED: 1


test:
  stage: test
  image: ubuntu:latest

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - my_babel_py/config.py
        - .gitlab-ci.yml

  before_script:
    - apt-get update
    - apt-get install -y libicu-dev python3-dev
    - python3 -m pip install pyicu gmpy2 pillow coverage

  script:
    - python3 main-cli.py info
    - python3 -m coverage run -m unittest discover
    - python3 -m coverage report -m


build:linux:
  stage: build
  image: condaforge/mambaforge:latest
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - mamba install -y gmpy2 pyicu pillow fpdf2 nuitka
  script:
    - python main-cli.py info


build:windows:
  stage: build
  tags:
    - saas-windows-medium-amd64
  rules:
    - if: $CI_COMMIT_TAG

  before_script:
    - wget.exe -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/2025-02-21/msys2-base-x86_64-20250221.sfx.exe
    - ./msys2.exe -y -oC:\
    - Remove-Item msys2.exe
    - $env:CHERE_INVOKING = 'yes' # for the shell to stay in the current working directory
    - $env:MSYSTEM = 'UCRT64'
    - C:\msys64\usr\bin\bash -lc ' ' # Run for the first time
    - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu' # Core update
    - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu' # Normal update
    - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S pactoys'
    - C:\msys64\usr\bin\bash -lc 'pacboy --noconfirm -S python-gmpy2:p python-icu:p python-pillow:p python-fpdf2:p python-nuitka:p'

  script:
    - C:\msys64\usr\bin\bash -lc 'python main-cli.py info'


build:macos:
  stage: build
  tags:
    - saas-macos-medium-m1
  image: macos-26-xcode-26
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - brew install icu4c
    - pip install -q gmpy2 pyicu pillow fpdf2 nuitka
  script:
    - python main-cli.py info
